# Generated by Django 5.2.4 on 2025-11-30 02:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("basic", "Usuario Básico"),
                            ("pro", "Usuario Pro"),
                            ("premium", "Usuario Premium"),
                            ("admin", "Administrador"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Masculino"),
                            ("female", "Femenino"),
                            ("other", "Otro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True,
                        help_text="Altura en centímetros",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True,
                        help_text="Peso en kilogramos",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "target_weight",
                    models.FloatField(
                        blank=True,
                        help_text="Peso objetivo en kg",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Sedentario"),
                            ("light", "Ligero"),
                            ("moderate", "Moderado"),
                            ("active", "Activo"),
                            ("very_active", "Muy Activo"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "main_goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lose_weight", "Perder peso"),
                            ("gain_muscle", "Ganar músculo"),
                            ("body_recomposition", "Recomposición corporal"),
                            ("maintain", "Mantener"),
                            ("performance", "Rendimiento"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "training_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "Casa"),
                            ("gym", "Gimnasio"),
                            ("outdoor", "Exterior"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "training_days_per_week",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "training_days",
                    models.JSONField(
                        default=list,
                        help_text="Días que entrena [1=Lunes, ..., 7=Domingo]",
                    ),
                ),
                (
                    "equipment_available",
                    models.JSONField(default=list, help_text="Equipamiento disponible"),
                ),
                (
                    "dietary_restrictions",
                    models.JSONField(
                        default=list,
                        help_text="['vegetarian', 'vegan', 'gluten-free', etc.]",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        default=list, help_text="['nuts', 'dairy', 'shellfish', etc.]"
                    ),
                ),
                (
                    "disliked_foods",
                    models.TextField(
                        blank=True, help_text="Alimentos que no come", null=True
                    ),
                ),
                (
                    "medical_conditions",
                    models.JSONField(
                        default=list, help_text="Condiciones médicas relevantes"
                    ),
                ),
                (
                    "injuries_or_medical_issues",
                    models.TextField(
                        blank=True, help_text="Lesiones o issues médicos", null=True
                    ),
                ),
                (
                    "daily_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Racha actual de días consecutivos"
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0, help_text="Racha más larga alcanzada"
                    ),
                ),
                (
                    "last_completed_day",
                    models.DateField(
                        blank=True, help_text="Última fecha con día completo", null=True
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        default=dict, help_text="Preferencias de notificaciones"
                    ),
                ),
                (
                    "workout_preferences",
                    models.JSONField(
                        default=dict, help_text="Preferencias de entrenamiento"
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False, help_text="Si completó el formulario inicial"
                    ),
                ),
                (
                    "onboarding_step",
                    models.PositiveIntegerField(
                        default=0, help_text="Paso actual del onboarding"
                    ),
                ),
                (
                    "password_reset_token",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("password_reset_expires", models.DateTimeField(blank=True, null=True)),
                ("must_change_password", models.BooleanField(default=False)),
                ("temporary_password_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
