# Generated by Django 5.2.4 on 2025-12-25 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_audit_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.FloatField(
                blank=True,
                help_text="Altura en centímetros",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(210),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="target_weight",
            field=models.FloatField(
                blank=True,
                help_text="Peso objetivo en kg",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
