# Generated by Django 5.2.4 on 2026-01-23 17:51

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="allergies",
            field=accounts.fields.EncryptedJSONField(
                default=list, help_text="['nuts', 'dairy', 'shellfish', etc.]"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="dietary_restrictions",
            field=accounts.fields.EncryptedJSONField(
                default=list, help_text="['vegetarian', 'vegan', 'gluten-free', etc.]"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="disliked_foods",
            field=accounts.fields.EncryptedTextField(
                blank=True, help_text="Alimentos que no come", null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=accounts.fields.EncryptedCharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="injuries_or_medical_issues",
            field=accounts.fields.EncryptedTextField(
                blank=True, help_text="Lesiones o issues médicos", null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=accounts.fields.EncryptedCharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="medical_conditions",
            field=accounts.fields.EncryptedJSONField(
                default=list, help_text="Condiciones médicas relevantes"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=accounts.fields.EncryptedCharField(
                blank=True, max_length=500, null=True
            ),
        ),
    ]
