# Generated by Django 5.2.4 on 2026-05-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customuser_membership_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="admin_calories_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Calorías diarias fijadas manualmente por un administrador. Si se establece, tiene prioridad sobre el cálculo automático.",
                null=True,
            ),
        ),
    ]
