# Generated by Django 5.2.4 on 2026-01-23 09:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("brand", models.CharField(blank=True, max_length=100)),
                (
                    "serving_size",
                    models.DecimalField(decimal_places=2, default=100, max_digits=8),
                ),
                (
                    "serving_unit",
                    models.CharField(
                        default="g", help_text="g, ml, unidad, etc.", max_length=30
                    ),
                ),
                ("calories", models.PositiveIntegerField(default=0)),
                (
                    "protein",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "carbs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("fat", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                (
                    "fiber",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sugar",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sodium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alimento",
                "verbose_name_plural": "Alimentos",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Nombre del plan", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción del plan"),
                ),
                (
                    "daily_calories",
                    models.PositiveIntegerField(
                        default=2000, help_text="Calorías diarias objetivo"
                    ),
                ),
                (
                    "protein_grams",
                    models.PositiveIntegerField(
                        default=150, help_text="Proteínas diarias en gramos"
                    ),
                ),
                (
                    "carbs_grams",
                    models.PositiveIntegerField(
                        default=200, help_text="Carbohidratos diarios en gramos"
                    ),
                ),
                (
                    "fat_grams",
                    models.PositiveIntegerField(
                        default=65, help_text="Grasas diarias en gramos"
                    ),
                ),
                (
                    "fiber_grams",
                    models.PositiveIntegerField(
                        default=25, help_text="Fibra diaria en gramos"
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("lose_weight", "Perder peso"),
                            ("gain_muscle", "Ganar músculo"),
                            ("maintain", "Mantener peso"),
                            ("body_recomposition", "Recomposición corporal"),
                            ("performance", "Rendimiento deportivo"),
                        ],
                        default="maintain",
                        max_length=50,
                    ),
                ),
                (
                    "diet_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("vegetarian", "Vegetariano"),
                            ("vegan", "Vegano"),
                            ("keto", "Keto"),
                            ("paleo", "Paleo"),
                            ("mediterranean", "Mediterránea"),
                            ("low_carb", "Bajo en carbohidratos"),
                            ("high_protein", "Alto en proteínas"),
                        ],
                        default="normal",
                        max_length=50,
                    ),
                ),
                (
                    "meals_per_day",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Comidas por día (típico: 5 = Desayuno, Snack, Almuerzo, Snack, Cena)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        default=4, help_text="Duración en semanas"
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False, help_text="True = plantilla reutilizable"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="True = plan del sistema"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False = plan inactivo"
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("image_url", models.URLField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nutrition_plans_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario (null = plantilla/sistema)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Nutrición",
                "verbose_name_plural": "Planes de Nutrición",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NutritionPlanHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("old_plan_name", models.CharField(blank=True, max_length=200)),
                ("new_plan_name", models.CharField(blank=True, max_length=200)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("user_request", "Solicitud del usuario"),
                            ("admin_change", "Cambio por administrador"),
                            ("auto_assigned", "Asignación automática"),
                            ("goal_change", "Cambio de objetivo"),
                            ("upgrade", "Actualización de plan"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nutrition_changes_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_as_new",
                        to="nutrition.nutritionplan",
                    ),
                ),
                (
                    "old_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_as_old",
                        to="nutrition.nutritionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrition_plan_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Plan Nutricional",
                "verbose_name_plural": "Historial de Planes Nutricionales",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Nombre de la receta", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción breve"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("breakfast", "Desayuno"),
                            ("lunch", "Almuerzo"),
                            ("dinner", "Cena"),
                            ("snack", "Snack"),
                            ("dessert", "Postre"),
                            ("drink", "Bebida"),
                        ],
                        default="lunch",
                        help_text="Categoría principal",
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Fácil"),
                            ("medium", "Medio"),
                            ("hard", "Difícil"),
                        ],
                        default="easy",
                        max_length=20,
                    ),
                ),
                (
                    "prep_time_minutes",
                    models.PositiveIntegerField(
                        default=15, help_text="Tiempo de preparación en minutos"
                    ),
                ),
                (
                    "cook_time_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Tiempo de cocción en minutos"
                    ),
                ),
                (
                    "servings",
                    models.PositiveIntegerField(
                        default=1, help_text="Número de porciones"
                    ),
                ),
                (
                    "calories",
                    models.PositiveIntegerField(
                        default=0, help_text="Calorías por porción"
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Proteínas en gramos",
                        max_digits=6,
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Carbohidratos en gramos",
                        max_digits=6,
                    ),
                ),
                (
                    "fat",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Grasas en gramos",
                        max_digits=6,
                    ),
                ),
                (
                    "fiber",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fibra en gramos",
                        max_digits=6,
                    ),
                ),
                (
                    "sugar",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Azúcar en gramos",
                        max_digits=6,
                    ),
                ),
                (
                    "sodium",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sodio en mg",
                        max_digits=8,
                    ),
                ),
                (
                    "ingredients",
                    models.JSONField(
                        default=list,
                        help_text="Lista de ingredientes: [{'name': 'Pollo', 'amount': '200', 'unit': 'g'}]",
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Instrucciones de preparación"
                    ),
                ),
                (
                    "diet_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tipos de dieta: ['vegetarian', 'vegan', 'gluten-free', 'keto', 'paleo']",
                    ),
                ),
                (
                    "meal_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tipos de comida: ['breakfast', 'lunch', 'dinner', 'snack', 'pre-workout', 'post-workout']",
                    ),
                ),
                (
                    "allergens",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Alérgenos: ['gluten', 'dairy', 'eggs', 'nuts', 'soy', 'shellfish']",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="Etiquetas adicionales"
                    ),
                ),
                ("image_url", models.URLField(blank=True, help_text="URL de imagen")),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="URL de video de preparación"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="True = receta del sistema"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False = receta desactivada"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="True = receta destacada"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recipes_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta",
                "verbose_name_plural": "Recetas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlanMeal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Lunes"),
                            (2, "Martes"),
                            (3, "Miércoles"),
                            (4, "Jueves"),
                            (5, "Viernes"),
                            (6, "Sábado"),
                            (7, "Domingo"),
                        ],
                        help_text="Día de la semana (1=Lunes..7=Domingo). Null = aplica a cualquier día.",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la comida (ej: 'Desayuno energético')",
                        max_length=200,
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Desayuno"),
                            ("morning_snack", "Snack Mañana"),
                            ("lunch", "Almuerzo"),
                            ("afternoon_snack", "Snack Tarde"),
                            ("dinner", "Cena"),
                            ("evening_snack", "Snack Noche"),
                            ("pre_workout", "Pre-Entreno"),
                            ("post_workout", "Post-Entreno"),
                        ],
                        default="lunch",
                        max_length=50,
                    ),
                ),
                (
                    "time",
                    models.TimeField(blank=True, help_text="Hora sugerida", null=True),
                ),
                (
                    "calories",
                    models.PositiveIntegerField(
                        default=400, help_text="Calorías objetivo"
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        decimal_places=2,
                        default=30,
                        help_text="Proteínas en gramos",
                        max_digits=6,
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        decimal_places=2,
                        default=40,
                        help_text="Carbohidratos en gramos",
                        max_digits=6,
                    ),
                ),
                (
                    "fat",
                    models.DecimalField(
                        decimal_places=2,
                        default=15,
                        help_text="Grasas en gramos",
                        max_digits=6,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción o sugerencias"),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(default=1, help_text="Orden en el día"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="nutrition.nutritionplan",
                    ),
                ),
                (
                    "suggested_recipes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Recetas sugeridas para esta comida",
                        related_name="suggested_in_meals",
                        to="nutrition.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comida en Plan",
                "verbose_name_plural": "Comidas en Plan",
                "ordering": ["day_of_week", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="MealLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="Fecha de la comida")),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Desayuno"),
                            ("morning_snack", "Snack Mañana"),
                            ("lunch", "Almuerzo"),
                            ("afternoon_snack", "Snack Tarde"),
                            ("dinner", "Cena"),
                            ("evening_snack", "Snack Noche"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True, help_text="Hora de la comida", null=True
                    ),
                ),
                (
                    "custom_description",
                    models.TextField(
                        blank=True, help_text="Descripción si no usó receta"
                    ),
                ),
                (
                    "calories",
                    models.PositiveIntegerField(
                        blank=True, help_text="Calorías consumidas", null=True
                    ),
                ),
                (
                    "protein",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "carbs",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "fat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "servings",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Número de porciones consumidas",
                        max_digits=4,
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=True, help_text="Si terminó la comida"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Valoración (1-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="meal_logs/%Y/%m/%d/"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_meal",
                    models.ForeignKey(
                        blank=True,
                        help_text="Comida del plan (slot). Si existe, identifica la selección de forma única.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="nutrition.planmeal",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        help_text="Receta usada (si aplica)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="nutrition.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Comida",
                "verbose_name_plural": "Logs de Comidas",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="PlanMealRecipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "servings",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Número de porciones personalizado (por defecto 1.0 = valores originales de la receta)",
                        max_digits=4,
                    ),
                ),
                (
                    "custom_calories",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Calorías personalizadas (null = calcular desde receta * servings)",
                        null=True,
                    ),
                ),
                (
                    "custom_protein",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Proteínas personalizadas en gramos (null = calcular desde receta * servings)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "custom_carbs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Carbohidratos personalizados en gramos (null = calcular desde receta * servings)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "custom_fat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Grasas personalizadas en gramos (null = calcular desde receta * servings)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de visualización (menor = primero)"
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_recipes",
                        to="nutrition.planmeal",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_suggestions",
                        to="nutrition.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta Sugerida en Comida",
                "verbose_name_plural": "Recetas Sugeridas en Comidas",
                "ordering": ["display_order", "created_at"],
                "unique_together": {("meal", "recipe")},
            },
        ),
    ]
