# Generated by Django 5.2.4 on 2025-12-23 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("nutrition", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingPlanAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_calories", models.IntegerField()),
                ("current_protein", models.IntegerField()),
                ("current_carbs", models.IntegerField()),
                ("current_fat", models.IntegerField()),
                ("proposed_calories", models.IntegerField()),
                ("proposed_protein", models.IntegerField()),
                ("proposed_carbs", models.IntegerField()),
                ("proposed_fat", models.IntegerField()),
                ("reason", models.CharField(max_length=200)),
                ("reason_detail", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("weight_change", "Cambio de peso"),
                            ("goal_change", "Cambio de objetivo"),
                            ("activity_change", "Cambio de nivel de actividad"),
                            ("manual", "Ajuste manual"),
                        ],
                        default="weight_change",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("expired", "Expirado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_adjustment",
                        to="notifications.notification",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_adjustments",
                        to="nutrition.nutritionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_plan_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ajuste de Plan Pendiente",
                "verbose_name_plural": "Ajustes de Plan Pendientes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="nutrition_p_user_id_a55e31_idx"
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="nutrition_p_status_b15451_idx",
                    ),
                ],
            },
        ),
    ]
