# Generated by Django 5.2.4 on 2025-12-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0002_pendingplanadjustment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingPlanAdjustment",
        ),
    ]
