# Generated by Django 5.2.4 on 2025-12-31 13:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0003_remove_pending_plan_adjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanMealRecipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "servings",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Número de porciones personalizado (por defecto 1.0 = valores originales de la receta)",
                        max_digits=4,
                    ),
                ),
                (
                    "custom_calories",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Calorías personalizadas (null = calcular desde receta * servings)",
                        null=True,
                    ),
                ),
                (
                    "custom_protein",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Proteínas personalizadas en gramos (null = calcular desde receta * servings)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "custom_carbs",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Carbohidratos personalizados en gramos (null = calcular desde receta * servings)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "custom_fat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Grasas personalizadas en gramos (null = calcular desde receta * servings)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de visualización (menor = primero)"
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_recipes",
                        to="nutrition.planmeal",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_suggestions",
                        to="nutrition.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta Sugerida en Comida",
                "verbose_name_plural": "Recetas Sugeridas en Comidas",
                "ordering": ["display_order", "created_at"],
                "unique_together": {("meal", "recipe")},
            },
        ),
    ]
