# Generated by Django 5.2.4 on 2025-12-31 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0003_remove_pending_plan_adjustment"),
    ]

    operations = [
        # No-op intencional: PlanMealRecipe ya se creó en 0001_initial.
    ]
