# Generated by Django 5.2.4 on 2026-01-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0004_add_plan_meal_recipe_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="planmeal",
            name="day_of_week",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Lunes"),
                    (2, "Martes"),
                    (3, "Miércoles"),
                    (4, "Jueves"),
                    (5, "Viernes"),
                    (6, "Sábado"),
                    (7, "Domingo"),
                ],
                help_text="Día de la semana (1=Lunes..7=Domingo). Null = aplica a cualquier día.",
                null=True,
            ),
        ),
    ]

