# Generated by Django 5.2.4 on 2026-01-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0004_add_plan_meal_recipe_model"),
    ]

    operations = [
        # No-op intencional: day_of_week ya existe en 0001_initial.
    ]

