# Generated by Django 5.2.4 on 2026-01-15 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0005_add_day_of_week_to_planmeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="meallog",
            name="plan_meal",
            field=models.ForeignKey(
                blank=True,
                help_text="Comida del plan (slot). Si existe, identifica la selección de forma única.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logs",
                to="nutrition.planmeal",
            ),
        ),
    ]

