# Generated by Django 5.2.4 on 2026-01-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0005_add_day_of_week_to_planmeal"),
    ]

    operations = [
        # No-op intencional: plan_meal ya existe en 0001_initial.
    ]

