# Generated by Django 5.2.4 on 2026-01-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0006_add_plan_meal_to_meallog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meallog",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Desayuno"),
                    ("lunch", "Comida"),
                    ("snack", "Merienda"),
                    ("dinner", "Cena"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="planmeal",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Desayuno"),
                    ("lunch", "Comida"),
                    ("snack", "Merienda"),
                    ("dinner", "Cena"),
                ],
                default="lunch",
                max_length=50,
            ),
        ),
    ]
