# Generated by Django 5.2.4 on 2026-01-29 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0007_update_meal_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Cantidad en gramos",
                        max_digits=8,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        default="g", help_text="Unidad de medida", max_length=30
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="used_in_recipes",
                        to="nutrition.food",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_ingredients",
                        to="nutrition.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente de receta",
                "verbose_name_plural": "Ingredientes de receta",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
