# Generated by Django 5.2.4 on 2026-02-05 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0008_add_recipe_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='carbs_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='% de calorías de carbohidratos (opcional)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='fat_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='% de calorías de grasa (opcional)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='protein_percentage',
            field=models.PositiveIntegerField(blank=True, help_text='% de calorías de proteína (opcional)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
