# Generated by Django 5.2.4 on 2026-02-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0009_add_macro_percentages"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionplan",
            name="portion_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Multiplicador de porciones (0.8 = 80%, 1.0 = 100%, 1.2 = 120%)",
                max_digits=4,
            ),
        ),
    ]
