# Generated by Django 5.2.4 on 2026-02-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0010_add_portion_multiplier_to_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="store",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mercadona", "Mercadona"),
                    ("carrefour", "Carrefour"),
                    ("lidl", "Lidl"),
                    ("aldi", "Aldi"),
                    ("dia", "Día"),
                    ("alcampo", "Alcampo"),
                    ("eroski", "Eroski"),
                    ("consum", "Consum"),
                    ("hipercor", "Hipercor"),
                    ("otro", "Otro"),
                ],
                help_text="Supermercado donde se puede encontrar",
                max_length=50,
            ),
        ),
    ]
