# Generated by ChatGPT on 2026-02-11

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0011_add_store_to_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeGoalVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.CharField(choices=[('lose_weight', 'Perder peso'), ('gain_muscle', 'Ganar músculo'), ('maintain', 'Mantener peso'), ('body_recomposition', 'Recomposición corporal'), ('performance', 'Rendimiento deportivo')], max_length=30)),
                ('portion_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador de porción para este objetivo', max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_variants', to='nutrition.recipe')),
            ],
            options={
                'verbose_name': 'Variante por objetivo',
                'verbose_name_plural': 'Variantes por objetivo',
                'unique_together': {('recipe', 'goal')},
            },
        ),
    ]
