# Generated by ChatGPT on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0013_add_recipe_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='goal_category',
            field=models.CharField(blank=True, choices=[('', 'Sin objetivo'), ('lose_weight', 'Perder peso'), ('gain_muscle', 'Ganar músculo'), ('maintain', 'Mantener peso'), ('body_recomposition', 'Recomposición corporal'), ('performance', 'Rendimiento deportivo')], default='', help_text='Objetivo principal para filtrar recetas', max_length=30),
        ),
    ]
