# Generated by ChatGPT on 2026-02-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0014_add_goal_category_to_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeGoalVariant',
        ),
    ]
