# Generated by Django 5.2.4 on 2026-03-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0017_change_recipe_choices_to_spanish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("desayuno", "Desayuno"),
                    ("almuerzo", "Almuerzo"),
                    ("cena", "Cena"),
                    ("snack", "Snack"),
                    ("postre", "Postre"),
                    ("bebida", "Bebida"),
                ],
                default="almuerzo",
                help_text="Categoría principal",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("fácil", "Fácil"),
                    ("medio", "Medio"),
                    ("difícil", "Difícil"),
                ],
                default="fácil",
                max_length=20,
            ),
        ),
    ]
