# Generated by Django 5.2.4 on 2026-03-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0019_capitalize_recipe_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("Desayuno", "Desayuno"),
                    ("Almuerzo", "Almuerzo"),
                    ("Cena", "Cena"),
                    ("Snack", "Snack"),
                    ("Postre", "Postre"),
                    ("Bebida", "Bebida"),
                ],
                default="Almuerzo",
                help_text="Categoría principal",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("Fácil", "Fácil"),
                    ("Medio", "Medio"),
                    ("Difícil", "Difícil"),
                ],
                default="Fácil",
                max_length=20,
            ),
        ),
    ]
