# Generated by Django 5.2.4 on 2026-03-19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0020_alter_recipe_category_alter_recipe_difficulty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meallog",
            name="is_skipped",
            field=models.BooleanField(
                default=False,
                help_text="Si el usuario marcó esta comida como 'no como'",
            ),
        ),
        migrations.AddField(
            model_name="meallog",
            name="skip_reason",
            field=models.TextField(
                blank=True,
                help_text="Motivo opcional por el que se saltó la comida",
            ),
        ),
        migrations.CreateModel(
            name="MealRecipeExclusion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_exclusions",
                        to="nutrition.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excluded_meal_recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exclusión de receta",
                "verbose_name_plural": "Exclusiones de recetas",
            },
        ),
        migrations.AddIndex(
            model_name="mealrecipeexclusion",
            index=models.Index(fields=["user", "is_active"], name="nutrition_m_user_id_08fa6d_idx"),
        ),
        migrations.AddIndex(
            model_name="mealrecipeexclusion",
            index=models.Index(fields=["recipe", "is_active"], name="nutrition_m_recipe__7d6a04_idx"),
        ),
        migrations.AddConstraint(
            model_name="mealrecipeexclusion",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"),
                name="unique_user_recipe_exclusion",
            ),
        ),
    ]
