# Generated by Django 5.2.4 on 2026-03-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0022_mealingredientexclusion"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="mealingredientexclusion",
            new_name="nutrition_m_user_id_b4edf6_idx",
            old_name="nutrition_me_user_id_c83f0c_idx",
        ),
        migrations.RenameIndex(
            model_name="mealingredientexclusion",
            new_name="nutrition_m_term_e9b2c6_idx",
            old_name="nutrition_me_term_8cc6dd_idx",
        ),
        migrations.RenameIndex(
            model_name="mealrecipeexclusion",
            new_name="nutrition_m_user_id_ee64d8_idx",
            old_name="nutrition_m_user_id_08fa6d_idx",
        ),
        migrations.RenameIndex(
            model_name="mealrecipeexclusion",
            new_name="nutrition_m_recipe__b9882a_idx",
            old_name="nutrition_m_recipe__7d6a04_idx",
        ),
    ]
