# Generated by Django 5.2.4 on 2026-05-26 09:55

import django.db.models.deletion
import nutrition.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0024_food_allergens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityRecipePost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to=nutrition.models.community_recipe_image_path)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_recipe_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación de receta de comunidad',
                'verbose_name_plural': 'Publicaciones de recetas de comunidad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityRecipeLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_recipe_likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='nutrition.communityrecipepost')),
            ],
            options={
                'verbose_name': 'Like de receta de comunidad',
                'verbose_name_plural': 'Likes de recetas de comunidad',
            },
        ),
        migrations.CreateModel(
            name='CommunityRecipeComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_recipe_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nutrition.communityrecipepost')),
            ],
            options={
                'verbose_name': 'Comentario de receta de comunidad',
                'verbose_name_plural': 'Comentarios de recetas de comunidad',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communityrecipepost',
            index=models.Index(fields=['expires_at', 'created_at'], name='nutrition_c_expires_c13a00_idx'),
        ),
        migrations.AddIndex(
            model_name='communityrecipepost',
            index=models.Index(fields=['author', 'created_at'], name='nutrition_c_author__ac1d42_idx'),
        ),
        migrations.AddIndex(
            model_name='communityrecipelike',
            index=models.Index(fields=['post', 'user'], name='nutrition_c_post_id_84e7b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='communityrecipelike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_community_recipe_like'),
        ),
        migrations.AddIndex(
            model_name='communityrecipecomment',
            index=models.Index(fields=['post', 'created_at'], name='nutrition_c_post_id_2632e4_idx'),
        ),
    ]
