# Generated by Django 5.2.4 on 2026-05-27 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0027_food_equivalence_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEquivalenceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_food_equivalence_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de equivalencia',
                'verbose_name_plural': 'Grupos de equivalencia',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='equivalence_groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos personalizados usados para recomendaciones de equivalencias.', related_name='foods', to='nutrition.foodequivalencegroup'),
        ),
    ]
