# Generated by Django 5.2.4 on 2026-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0028_equivalencecategory_food_equivalence_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equivalencecategory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='equivalence_category',
            field=models.CharField(blank=True, db_index=True, help_text='Grupo principal de equivalencia (legacy, se mantiene para compatibilidad)', max_length=50),
        ),
    ]
