# Generated by Django 5.2.4 on 2025-11-30 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MotivationalTip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(help_text="Título del consejo", max_length=200),
                ),
                ("content", models.TextField(help_text="Contenido del consejo")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("motivation", "Motivación"),
                            ("nutrition", "Nutrición"),
                            ("workout", "Entrenamiento"),
                            ("mindset", "Mentalidad"),
                            ("recovery", "Recuperación"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Si el consejo está activo"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=1, help_text="Prioridad del consejo (1-10)"
                    ),
                ),
                (
                    "last_shown",
                    models.DateTimeField(
                        blank=True, help_text="Última vez que se mostró", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Consejo Motivacional",
                "verbose_name_plural": "Consejos Motivacionales",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.CharField(help_text="Asunto del mensaje", max_length=200),
                ),
                ("message", models.TextField(help_text="Contenido del mensaje")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bug", "Error/Bug"),
                            ("feature", "Nueva Funcionalidad"),
                            ("improvement", "Mejora"),
                            ("complaint", "Queja"),
                            ("compliment", "Elogio"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("urgent", "Urgente"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nuevo"),
                            ("in_progress", "En Progreso"),
                            ("resolved", "Resuelto"),
                            ("closed", "Cerrado"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "admin_response",
                    models.TextField(
                        blank=True, help_text="Respuesta del administrador"
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Feedback",
                "verbose_name_plural": "Mensajes de Feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("workout_reminder", "Recordatorio de entrenamiento"),
                            ("meal_reminder", "Recordatorio de comida"),
                            ("achievement", "Logro desbloqueado"),
                            ("progress", "Actualización de progreso"),
                            ("system", "Notificación del sistema"),
                            ("nutrition", "Notificación nutricional"),
                            ("workout", "Notificación de entrenamiento"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, null=True)),
                ("action_url", models.URLField(blank=True, default="")),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read_at"],
                        name="notificatio_user_id_47e85c_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_c62b26_idx",
                    ),
                    models.Index(
                        fields=["user", "type"], name="notificatio_user_id_827754_idx"
                    ),
                ],
            },
        ),
    ]
