# Generated by Django 5.2.4 on 2025-12-23 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "endpoint",
                    models.URLField(
                        help_text="URL del endpoint de push", max_length=500
                    ),
                ),
                (
                    "p256dh",
                    models.CharField(help_text="Clave pública p256dh", max_length=200),
                ),
                (
                    "auth",
                    models.CharField(
                        help_text="Clave de autenticación", max_length=200
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Si la suscripción está activa"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User agent del navegador"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción Push",
                "verbose_name_plural": "Suscripciones Push",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="notificatio_user_id_1159a5_idx",
                    ),
                    models.Index(
                        fields=["endpoint"], name="notificatio_endpoin_498a4c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "endpoint"), name="unique_user_endpoint"
                    )
                ],
            },
        ),
    ]
