# Generated by Django 5.2.4 on 2026-03-19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_add_push_subscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(help_text="Título del mensaje", max_length=200),
                ),
                ("message", models.TextField(help_text="Contenido del mensaje")),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL para acción (opcional)",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, help_text="Cuándo fue leído"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, help_text="Expiración del mensaje"
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_admin_messages",
                        to=settings.AUTH_USER_MODEL,
                        help_text="Admin que envió el mensaje",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Admin",
                "verbose_name_plural": "Mensajes de Admin",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read_at"],
                        name="notificatio_user_id_0a7e5d_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notificatio_user_id_7785a5_idx",
                    ),
                    models.Index(
                        fields=["sent_by", "created_at"],
                        name="notificatio_sent_by_b287e8_idx",
                    ),
                ],
            },
        ),
    ]
