# Generated by Django 5.2.4 on 2026-03-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_adminmessage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminmessage",
            new_name="notificatio_user_id_7cceb8_idx",
            old_name="notificatio_user_id_0a7e5d_idx",
        ),
        migrations.RenameIndex(
            model_name="adminmessage",
            new_name="notificatio_user_id_19ac30_idx",
            old_name="notificatio_user_id_7785a5_idx",
        ),
        migrations.RenameIndex(
            model_name="adminmessage",
            new_name="notificatio_sent_by_4c587e_idx",
            old_name="notificatio_sent_by_b287e8_idx",
        ),
    ]
