"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import logging

# ---------------------------------
# Directorio base
# ---------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Soporte opcional para HEIC/HEIF (fotos iOS)
try:
    import pillow_heif
    pillow_heif.register_heif_opener()
except Exception:
    pass

# Cargar variables de entorno desde .env solo cuando se solicita explícitamente,
# en entornos de desarrollo o al ejecutar tests. Evita contaminar producción con valores locales.
_read_dotenv_raw = os.getenv("READ_DOTENV")
if _read_dotenv_raw is None:
    READ_DOTENV = os.getenv("DEBUG", "True") == "True" or "test" in sys.argv
else:
    READ_DOTENV = _read_dotenv_raw == "True"

if READ_DOTENV:
    load_dotenv(BASE_DIR / ".env")

LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
IS_TESTING = "test" in sys.argv

# Importar configuración de logging
try:
    from .logging_config import LOGGING
except ImportError:
    LOGGING = {}  

# ---------------------------------
# Configuración general
# ---------------------------------
# Nunca hardcodees la clave en producción. Define SECRET_KEY en variables de entorno.
SECRET_KEY = os.getenv("SECRET_KEY", "dev-only-do-not-use-in-prod")

# Clave de encriptación para datos sensibles (Fernet base64)
ENCRYPTION_KEY = os.getenv("ENCRYPTION_KEY")

# DEBUG debe ser "True"/"False" (string) en el entorno. Por defecto True en local.
# ⚠️ IMPORTANTE: En producción, DEBUG debe ser "False" en backend.env.production
DEBUG = os.getenv("DEBUG", "True") == "True"

# Dominios permitidos. Ejemplo prod: "tu-api.onrender.com,tu-frontend.vercel.app"
ALLOWED_HOSTS = [h for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h]

# Opcional pero recomendado si hay proxy (Render/Fly/etc.)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# ---------------------------------
# Apps instaladas
# ---------------------------------
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Terceros
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "drf_spectacular",
    "django_redis",
    "django_celery_results",

    # Propias
    "api",
    "accounts",
    "nutrition",
    "workouts",
    "progress",
    "notifications",
    "achievements",
    "dashboard",
]

# ---------------------------------
# Middleware
#  - WhiteNoise para estáticos en prod
#  - corsheaders ANTES de CommonMiddleware
# ---------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # sirve estáticos en prod
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",       # debe ir antes de CommonMiddleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "api.middleware.ErrorReportMiddleware",
    "api.middleware.UTF8ResponseMiddleware",  # Asegurar UTF-8 en respuestas JSON
]

# ---------------------------------
# DRF + JWT
# ---------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",  # Renderer estándar primero
        "api.renderers.UTF8JSONRenderer",  # Renderer UTF-8 personalizado
        *(
            ["rest_framework.renderers.BrowsableAPIRenderer"]
            if DEBUG
            else []
        ),
    ],
    "UNICODE_JSON": True,  # Asegurar que JSON use Unicode (UTF-8)
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,  # Aumentado de 20 a 100 para mostrar más elementos
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",  # para scopes como 'login'
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "1000/min" if DEBUG else "100/min",
        "user": "2000/min" if DEBUG else "1000/min",  # Aumentado para mejor UX
        "login": "10/min",  # límite específico para intentos de login (aumentado)
        "register": "5/min",  # límite para registro
        "forgot_password": "5/min",  # límite para solicitar reset
        "reset_password": "10/min",  # límite para resetear contraseña
        "change_password": "20/min",  # límite para cambiar contraseña
        "admin_notifications_send": "60/hour" if DEBUG else "20/hour",
    },
    "EXCEPTION_HANDLER": "api.utils.custom_exception_handler",
}

# JWT Configuration
# ACCESS_TOKEN_LIFETIME: Tiempo de vida del token de acceso (1 hora por defecto)
# REFRESH_TOKEN_LIFETIME: Tiempo de vida del token de renovación (30 días por defecto)
# El token de acceso ahora dura 1 hora en lugar de 15 minutos para evitar cierres de sesión inesperados
def get_access_token_lifetime():
    """Obtiene el tiempo de vida del token de acceso desde variables de entorno"""
    # Por defecto: 2 horas para evitar cierres de sesión inesperados durante entrenamientos
    ttl_str = os.getenv("JWT_ACCESS_TTL", "120m")
    if "h" in ttl_str.lower():
        # Formato: "1h", "2h", etc.
        hours = int(ttl_str.lower().replace("h", "").strip())
        return timedelta(hours=hours)
    elif "m" in ttl_str.lower():
        # Formato: "60m", "120m", etc.
        minutes = int(ttl_str.lower().replace("m", "").strip())
        return timedelta(minutes=minutes)
    else:
        # Por defecto, asumir minutos
        return timedelta(minutes=int(ttl_str))

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": get_access_token_lifetime(),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_TTL", "30").replace("d", ""))),
    "ROTATE_REFRESH_TOKENS": os.getenv("JWT_ROTATE_REFRESH", "True") == "True",
    "BLACKLIST_AFTER_ROTATION": os.getenv("JWT_BLACKLIST_AFTER_ROTATION", "True") == "True",
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": os.getenv("JWT_SECRET", SECRET_KEY),
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "JTI_CLAIM": "jti",
    # Usar el serializer personalizado que incluye is_staff, is_superuser, role
    "TOKEN_OBTAIN_SERIALIZER": "api.auth_serializers.EmailTokenObtainPairSerializer",
}

# ---------------------------------
# CORS / CSRF
#  - En dev puedes permitir todo; en prod restringe a tu dominio de frontend
# ---------------------------------
# Si quieres permitir todo en dev y restringir en prod:
CORS_ALLOW_ALL_ORIGINS = DEBUG

# Si pones dominios específicos, configúralos por entorno:
# Ejemplo: "https://tu-frontend.vercel.app,http://localhost:3000"
CORS_ALLOWED_ORIGINS = [
    o for o in os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://192.168.1.148:3000").split(",") if o
]

# Para peticiones con cookies/sesión (si las usas)
CORS_ALLOW_CREDENTIALS = True

# Configuraciones adicionales para desarrollo
if DEBUG:
    # Permitir todos los orígenes en desarrollo
    CORS_ALLOW_ALL_ORIGINS = True
    # Permitir todos los headers
    CORS_ALLOW_ALL_HEADERS = True
    # Permitir todos los métodos
    CORS_ALLOW_ALL_METHODS = True
else:
    # En producción, usar solo los orígenes permitidos
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOW_HEADERS = [
        'accept',
        'accept-encoding',
        'accept-language',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-client-path',
        'x-client-url',
        'x-csrftoken',
        'x-requested-with',
        'cache-control',
        'pragma',
    ]
    CORS_ALLOW_METHODS = [
        'DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT',
    ]

# CSRF (necesario si usas cookies/CSRF en vez de solo JWT)
# Ejemplo: "https://tu-frontend.vercel.app,http://localhost:3000"
CSRF_TRUSTED_ORIGINS = [
    o for o in os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost:3000,http://192.168.1.148:3000").split(",") if o
]

def _get_frontend_url():
    configured_frontend_url = os.getenv("FRONTEND_URL")
    if configured_frontend_url:
        return configured_frontend_url.rstrip("/")

    https_origin = next(
        (origin for origin in CORS_ALLOWED_ORIGINS if origin.startswith("https://")),
        None,
    )
    fallback_origin = https_origin or (CORS_ALLOWED_ORIGINS[0] if CORS_ALLOWED_ORIGINS else "http://localhost:3000")
    return fallback_origin.rstrip("/")


FRONTEND_URL = _get_frontend_url()

# ---------------------------------
# URLs y WSGI
# ---------------------------------
ROOT_URLCONF = "backend.urls"
WSGI_APPLICATION = "backend.wsgi.application"

# ---------------------------------
# Templates
# ---------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # agrega rutas de templates si las necesitas
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ---------------------------------
# Base de datos (PostgreSQL)
# Define en entorno: DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT (5432)
# ---------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "OPTIONS": {
            "sslmode": os.getenv("DB_SSLMODE", "prefer"),
            "client_encoding": "UTF8",  # Asegurar UTF-8 en la conexión a PostgreSQL
            "options": "-c client_encoding=UTF8 -c lc_messages=en_US.UTF-8",  # Forzar UTF-8 en la conexión
        },
        # En producción, evitar conexiones persistentes largas: si Postgres reinicia, pueden quedar sockets rotos
        # y provocar 500 ("server closed the connection unexpectedly") en endpoints como login/me.
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60" if DEBUG else "0")),
        # Verificar salud de conexión al reutilizarla (Django 4.2+)
        "CONN_HEALTH_CHECKS": os.getenv("DB_CONN_HEALTH_CHECKS", "True") == "True",
        # PostgreSQL no admite COLLATION en creación de BD de test.
        "TEST": {},
    }
}

if IS_TESTING and os.getenv("USE_POSTGRES_FOR_TESTS", "False") != "True":
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "test.sqlite3",
    }

if IS_TESTING and os.getenv("USE_MIGRATIONS_FOR_TESTS", "False") != "True":
    class DisableMigrations(dict):
        def __contains__(self, item):
            return True

        def __getitem__(self, item):
            return None

    MIGRATION_MODULES = DisableMigrations()

# ---------------------------------
# Cache (Redis)
# ---------------------------------
if DEBUG:
    # En desarrollo, usar cache en memoria
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
    # Sesiones en base de datos para desarrollo
    SESSION_ENGINE = "django.contrib.sessions.backends.db"
else:
    # En producción, usar Redis
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.getenv("REDIS_URL", "redis://localhost:6379/0"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # Evita 500 si Redis no está disponible (throttling/cache fail-open)
                "IGNORE_EXCEPTIONS": True,
                # Timeouts cortos para no bloquear requests cuando Redis falla
                "SOCKET_CONNECT_TIMEOUT": 2,
                "SOCKET_TIMEOUT": 2,
            }
        }
    }
    # Cache como backend de sesiones en producción
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"

# ---------------------------------
# Email
# ---------------------------------
# Configuración de Email
def _get_env(*keys, default=""):
    """Obtiene el primer valor no vacío entre varias variables de entorno."""
    for key in keys:
        value = os.getenv(key)
        if value not in (None, ""):
            return value
    return default


smtp_host = _get_env("SMTP_HOST", "EMAIL_HOST", default="")

# En desarrollo, usar consola si no hay configuración SMTP/EMAIL.
if DEBUG and not smtp_host:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    # Los emails se mostrarán en la consola en desarrollo
else:
    EMAIL_BACKEND = _get_env("EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend")
    EMAIL_HOST = smtp_host
    EMAIL_PORT = int(_get_env("SMTP_PORT", "EMAIL_PORT", default="587"))
    EMAIL_HOST_USER = _get_env("SMTP_USER", "EMAIL_HOST_USER", default="")
    EMAIL_HOST_PASSWORD = _get_env("SMTP_PASSWORD", "EMAIL_HOST_PASSWORD", default="")
    EMAIL_USE_TLS = _get_env("SMTP_USE_TLS", "EMAIL_USE_TLS", default="True") == "True"
    EMAIL_USE_SSL = _get_env("SMTP_USE_SSL", "EMAIL_USE_SSL", default="False") == "True"
    EMAIL_TIMEOUT = int(_get_env("SMTP_TIMEOUT", "EMAIL_TIMEOUT", default="10"))

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "NexFit365 <no-reply@nex-fit.local>")

ERROR_REPORT_EMAILS = [
    email.strip()
    for email in os.getenv("ERROR_REPORT_EMAILS", "errors@example.invalid").split(",")
    if email.strip()
]
ERROR_REPORT_LOG_DIR = os.getenv("ERROR_REPORT_LOG_DIR", str(BASE_DIR / "logs" / "error-reports"))

# ---------------------------------
# Celery — cola de tareas asíncronas
# ---------------------------------
CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    os.getenv("REDIS_URL", "redis://redis:6379/1")
)
CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    os.getenv("REDIS_URL", "redis://redis:6379/1")
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = os.getenv("TIME_ZONE", "Europe/Madrid")
CELERY_TASK_ALWAYS_EAGER = os.getenv("CELERY_ALWAYS_EAGER", "False") == "True"  # True en tests
CELERY_TASK_EAGER_PROPAGATES = True
# Reintentos automáticos en caso de fallo del broker
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# ---------------------------------
# Media files
# ---------------------------------
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / os.getenv("UPLOAD_DIR", "media")

# Configuración de uploads
MAX_AVATAR_SIZE = int(os.getenv("MAX_AVATAR_MB", "2")) * 1024 * 1024  # en bytes
MAX_PROGRESS_PHOTO_SIZE = int(os.getenv("MAX_PROGRESS_PHOTO_MB", "5")) * 1024 * 1024
MAX_UPLOAD_SIZE = int(os.getenv("MAX_UPLOAD_MB", "300")) * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE

# ---------------------------------
# Validación de contraseñas
# ---------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ---------------------------------
# Internacionalización
# ---------------------------------
LANGUAGE_CODE = os.getenv("LANGUAGE_CODE", "es-es")
TIME_ZONE = os.getenv("TIME_ZONE", "Europe/Madrid")   # zona horaria del proyecto
USE_I18N = True
USE_TZ = True

# ---------------------------------
# Archivos estáticos
# ---------------------------------
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # para collectstatic en prod
# WhiteNoise: compresión y nombres con hash
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ---------------------------------
# Google Drive API (para videos de ejercicios)
# ---------------------------------
# ID de la carpeta de Google Drive donde están los videos
DEFAULT_GOOGLE_DRIVE_FOLDER_ID = "1dbDvVZKOwYJ4A13FtVslIid2JKLcN4fG"
GOOGLE_DRIVE_FOLDER_ID = (
    os.getenv("GOOGLE_DRIVE_FOLDER_ID")
    or os.getenv("NEXT_PUBLIC_GOOGLE_DRIVE_FOLDER_ID")
    or DEFAULT_GOOGLE_DRIVE_FOLDER_ID
)

# ---------------------------------
# Push Notifications (VAPID)
# ---------------------------------
VAPID_PUBLIC_KEY = os.getenv("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.getenv("VAPID_PRIVATE_KEY", "")
VAPID_CLAIM_EMAIL = os.getenv("VAPID_CLAIM_EMAIL", DEFAULT_FROM_EMAIL)

# Opción 1: Service Account (recomendado para backend)
# Ruta al archivo JSON de credenciales de Service Account
GOOGLE_DRIVE_CREDENTIALS_PATH = os.getenv("GOOGLE_DRIVE_CREDENTIALS_PATH", None)

# Opción 2: API Key (menos seguro, pero más simple)
GOOGLE_DRIVE_API_KEY = os.getenv("GOOGLE_DRIVE_API_KEY", None)

# ---------------------------------
# Clave por defecto para modelos
# ---------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------------------------
# Usuario custom
# ---------------------------------
AUTH_USER_MODEL = "accounts.CustomUser"

# ---------------------------------
# OpenAPI / Docs
# ---------------------------------
SPECTACULAR_SETTINGS = {
    "TITLE": "Nex-Fit API",
    "DESCRIPTION": "API completa para aplicación de fitness y nutrición con gestión de usuarios, entrenamientos, progreso y más.",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
            }
        }
    },
    "SECURITY": [{"BearerAuth": []}],  # botón Authorize en Swagger con Bearer
    "TAGS": [
        {"name": "Auth", "description": "Autenticación y gestión de usuarios"},
        {"name": "Users", "description": "Gestión de usuarios y perfiles"},
        {"name": "Nutrition", "description": "Planes nutricionales y logs de comidas"},
        {"name": "Workouts", "description": "Programas de entrenamiento y logs"},
        {"name": "Progress", "description": "Seguimiento de progreso y fotos"},
        {"name": "Notifications", "description": "Sistema de notificaciones"},
        {"name": "Achievements", "description": "Logros y badges"},
        {"name": "Dashboard", "description": "Dashboard y estadísticas"},
    ],
}

# ---------------------------------
# Cookies seguras en prod
# ---------------------------------
# Cookies seguras: solo True si usas HTTPS
# Leer de entorno, por defecto False si DEBUG=True, True si DEBUG=False
CSRF_COOKIE_SECURE = os.getenv("CSRF_COOKIE_SECURE", str(not DEBUG)) == "True"
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE", str(not DEBUG)) == "True"
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", str(not DEBUG)) == "True"
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0" if DEBUG else "31536000"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", str(not DEBUG)) == "True"
SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "False") == "True"
SECURE_CONTENT_TYPE_NOSNIFF = os.getenv("SECURE_CONTENT_TYPE_NOSNIFF", "True") == "True"
SECURE_REFERRER_POLICY = os.getenv("SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin")

# ---------------------------------
# Logging estructurado
# ---------------------------------
# La configuración de logging se importa desde logging_config.py
# Si no se puede importar, se usa una configuración básica
if not LOGGING:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "simple": {"format": "%(levelname)s %(name)s: %(message)s"},
            "verbose": {"format": "%(asctime)s %(levelname)s %(name)s [%(module)s:%(lineno)d] %(message)s"},
        },
        "handlers": {
            "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        },
        "root": {"handlers": ["console"], "level": LOG_LEVEL},
        "loggers": {
            "django": {"handlers": ["console"], "level": LOG_LEVEL, "propagate": False},
            "progress": {"handlers": ["console"], "level": "DEBUG", "propagate": False},
        },
    }
