# Generated by Django 5.2.4 on 2026-09-29 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('privacy', 'Privacidad'), ('terms', 'Términos'), ('health_notice', 'Aviso de datos de salud'), ('cookies', 'Cookies'), ('marketing', 'Marketing')], max_length=32)),
                ('version', models.CharField(max_length=32)),
                ('locale', models.CharField(default='es-ES', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('requires_acceptance', models.BooleanField(default=False)),
                ('requires_reacceptance', models.BooleanField(default=False)),
                ('withdrawable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code', 'locale', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('code', 'version', 'locale'), name='legal_document_version_unique'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('code', 'locale'), name='legal_one_active_per_code_locale')],
            },
        ),
        migrations.CreateModel(
            name='UserLegalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('account', 'Cuenta'), ('health_profile', 'Perfil de salud'), ('progress_photos', 'Fotos de progreso'), ('nutrition', 'Nutrición'), ('workouts', 'Entrenamiento'), ('wellness', 'Bienestar'), ('marketing', 'Marketing')], max_length=32)),
                ('event_type', models.CharField(choices=[('acknowledgement', 'Acuse'), ('acceptance', 'Aceptación'), ('consent_granted', 'Consentimiento otorgado'), ('consent_withdrawn', 'Consentimiento retirado')], max_length=32)),
                ('legal_basis', models.CharField(blank=True, choices=[('consent', 'Consentimiento'), ('contract', 'Contrato'), ('legal_obligation', 'Obligación legal'), ('legitimate_interest', 'Interés legítimo'), ('vital_interest', 'Interés vital'), ('public_task', 'Misión pública'), ('special_category_explicit_consent', 'Consentimiento explícito de categoría especial'), ('other', 'Otra')], max_length=64)),
                ('source', models.CharField(choices=[('registration', 'Registro'), ('initial_registration', 'Registro inicial'), ('settings', 'Ajustes'), ('reacceptance', 'Reaceptación'), ('admin', 'Administración'), ('api', 'API')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='legal.legaldocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'document', 'purpose', 'created_at'], name='legal_event_lookup')],
            },
        ),
    ]
