# Generated by Django 5.2.4 on 2025-11-30 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("data_type", models.CharField(max_length=50)),
                ("nutrition_data", models.JSONField(blank=True, null=True)),
                ("workout_data", models.JSONField(blank=True, null=True)),
                ("progress_data", models.JSONField(blank=True, null=True)),
                ("achievements_data", models.JSONField(blank=True, null=True)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Cuándo expira este cache"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_data",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="dashboard_d_user_id_d8f999_idx"
                    ),
                    models.Index(
                        fields=["user", "data_type"],
                        name="dashboard_d_user_id_248066_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="dashboard_d_expires_900daf_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "date", "data_type"),
                        name="unique_dashboard_data_per_user_date_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "calories_goal",
                    models.IntegerField(
                        default=2000, help_text="Objetivo de calorías diarias"
                    ),
                ),
                (
                    "workouts_goal",
                    models.IntegerField(
                        default=5, help_text="Objetivo de entrenamientos por semana"
                    ),
                ),
                (
                    "weight_goal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso objetivo en kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "current_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso actual en kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "starting_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso inicial en kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "transformation_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de inicio de la transformación",
                        null=True,
                    ),
                ),
                (
                    "next_review_date",
                    models.DateField(
                        blank=True, help_text="Próxima fecha de revisión", null=True
                    ),
                ),
                (
                    "preferred_workout_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Días preferidos para entrenar",
                    ),
                ),
                (
                    "preferred_meal_times",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Horarios preferidos para comer",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estadísticas del Usuario",
                "verbose_name_plural": "Estadísticas de los Usuarios",
                "indexes": [
                    models.Index(
                        fields=["user"], name="dashboard_u_user_id_a14332_idx"
                    ),
                    models.Index(
                        fields=["transformation_start_date"],
                        name="dashboard_u_transfo_627e36_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WellnessTip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("content", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nutrition", "Nutrición"),
                            ("training", "Entrenamiento"),
                            ("mindset", "Mentalidad"),
                            ("recovery", "Recuperación"),
                            ("lifestyle", "Estilo de vida"),
                        ],
                        default="mindset",
                        max_length=50,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        default="general",
                        help_text="Segmento de usuarios al que va dirigido el consejo (general, principiantes, avanzados, etc.).",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False,
                        help_text="Los consejos destacados se muestran primero en el dashboard.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wellness_tips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consejo de bienestar",
                "verbose_name_plural": "Consejos de bienestar",
                "ordering": ["-is_highlighted", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="dashboard_w_categor_33adcb_idx",
                    ),
                    models.Index(
                        fields=["is_highlighted", "is_active"],
                        name="dashboard_w_is_high_96f46e_idx",
                    ),
                ],
            },
        ),
    ]
