# Generated by Django 5.2.4 on 2025-12-04 22:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("nutrition", "0001_initial"),
        ("workouts", "0002_alter_workoutlog_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultPlanConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo de la configuración",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción detallada"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Prioridad de evaluación (menor número = mayor prioridad)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activa para asignación automática",
                    ),
                ),
                (
                    "main_goal",
                    models.CharField(
                        blank=True,
                        help_text="Objetivo principal del usuario (lose_weight, gain_muscle, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "training_location",
                    models.CharField(
                        blank=True,
                        help_text="Ubicación de entrenamiento (home, gym, outdoor)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        help_text="Nivel de actividad (sedentary, light, moderate, active, very_active)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        help_text="Género objetivo (male, female, other) - null para todos",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "min_training_days_per_week",
                    models.IntegerField(
                        blank=True,
                        help_text="Mínimo de días de entrenamiento por semana",
                        null=True,
                    ),
                ),
                (
                    "max_training_days_per_week",
                    models.IntegerField(
                        blank=True,
                        help_text="Máximo de días de entrenamiento por semana",
                        null=True,
                    ),
                ),
                (
                    "age_min",
                    models.IntegerField(
                        blank=True, help_text="Edad mínima del usuario", null=True
                    ),
                ),
                (
                    "age_max",
                    models.IntegerField(
                        blank=True, help_text="Edad máxima del usuario", null=True
                    ),
                ),
                (
                    "dietary_restrictions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de restricciones dietéticas a considerar",
                    ),
                ),
                (
                    "equipment_keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Palabras clave de equipamiento disponible",
                    ),
                ),
                (
                    "default_nutrition_plan",
                    models.ForeignKey(
                        blank=True,
                        help_text="Plan nutricional a asignar",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_configurations",
                        to="nutrition.nutritionplan",
                    ),
                ),
                (
                    "default_workout_program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Programa de entrenamiento a asignar",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_configurations",
                        to="workouts.workoutprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Plan por Defecto",
                "verbose_name_plural": "Configuraciones de Planes por Defecto",
                "ordering": ["priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["priority", "is_active"],
                        name="dashboard_d_priorit_625c5e_idx",
                    ),
                    models.Index(
                        fields=["main_goal", "training_location", "activity_level"],
                        name="dashboard_d_main_go_a76a03_idx",
                    ),
                ],
            },
        ),
    ]
