# Generated by Django 5.2.4 on 2025-12-23 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_defaultplanconfiguration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HelpSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faq_enabled",
                    models.BooleanField(
                        default=True, help_text="Activar página de FAQ"
                    ),
                ),
                (
                    "faq_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de la página de FAQ (si está en otra ubicación)",
                        null=True,
                    ),
                ),
                (
                    "faq_content",
                    models.TextField(
                        blank=True,
                        help_text="Contenido HTML de la página FAQ (si se gestiona internamente)",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="soporte@nexfit365.com",
                        help_text="Email de contacto para soporte",
                        max_length=254,
                    ),
                ),
                (
                    "contact_enabled",
                    models.BooleanField(
                        default=True, help_text="Activar contacto por email"
                    ),
                ),
                (
                    "guides_enabled",
                    models.BooleanField(
                        default=True, help_text="Activar página de guías"
                    ),
                ),
                (
                    "guides_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de la página de guías (si está en otra ubicación)",
                        null=True,
                    ),
                ),
                (
                    "guides_content",
                    models.TextField(
                        blank=True,
                        help_text="Contenido HTML de las guías (si se gestiona internamente)",
                    ),
                ),
                (
                    "report_enabled",
                    models.BooleanField(
                        default=True, help_text="Activar formulario de reporte"
                    ),
                ),
                (
                    "report_email",
                    models.EmailField(
                        default="soporte@nexfit365.com",
                        help_text="Email donde se envían los reportes de problemas",
                        max_length=254,
                    ),
                ),
                (
                    "report_redirect_url",
                    models.URLField(
                        blank=True,
                        help_text="URL a donde redirigir después de enviar el reporte",
                        null=True,
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        default="2.1.0",
                        help_text="Versión actual de la aplicación",
                        max_length=50,
                    ),
                ),
                (
                    "last_update_date",
                    models.CharField(
                        default="Diciembre 2024",
                        help_text="Fecha de última actualización",
                        max_length=100,
                    ),
                ),
                (
                    "terms_url",
                    models.URLField(
                        blank=True, help_text="URL de términos de servicio", null=True
                    ),
                ),
                (
                    "privacy_url",
                    models.URLField(
                        blank=True, help_text="URL de política de privacidad", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Activar esta configuración de ayuda"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Ayuda",
                "verbose_name_plural": "Configuraciones de Ayuda",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="unique_active_help_settings",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProblemReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem_type",
                    models.CharField(
                        choices=[
                            ("bug", "Error/Bug"),
                            ("feature", "Solicitud de Funcionalidad"),
                            ("ui", "Problema de Interfaz"),
                            ("performance", "Problema de Rendimiento"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        help_text="Tipo de problema",
                        max_length=50,
                    ),
                ),
                (
                    "subject",
                    models.CharField(help_text="Asunto del problema", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Descripción detallada del problema"),
                ),
                (
                    "steps_to_reproduce",
                    models.TextField(
                        blank=True, help_text="Pasos para reproducir el problema"
                    ),
                ),
                (
                    "expected_behavior",
                    models.TextField(blank=True, help_text="Comportamiento esperado"),
                ),
                (
                    "actual_behavior",
                    models.TextField(blank=True, help_text="Comportamiento actual"),
                ),
                (
                    "browser_info",
                    models.CharField(
                        blank=True,
                        help_text="Información del navegador",
                        max_length=200,
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True,
                        help_text="Información del dispositivo",
                        max_length=200,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="URL donde ocurrió el problema"
                    ),
                ),
                (
                    "screenshot_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de captura de pantalla si se adjuntó",
                        null=True,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email de contacto (si el usuario no está autenticado)",
                        max_length=254,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("in_review", "En Revisión"),
                            ("resolved", "Resuelto"),
                            ("closed", "Cerrado"),
                        ],
                        default="pending",
                        help_text="Estado del reporte",
                        max_length=50,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Notas del administrador"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de resolución", null=True
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Administrador que resolvió el problema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que reporta el problema (puede ser anónimo)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problem_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Problema",
                "verbose_name_plural": "Reportes de Problemas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="dashboard_p_status_b56155_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="dashboard_p_user_id_ac9ed2_idx",
                    ),
                    models.Index(
                        fields=["problem_type"], name="dashboard_p_problem_b5e6f7_idx"
                    ),
                ],
            },
        ),
    ]
