# Generated by Django 5.2.4 on 2026-04-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_coachinginquiry_source_screen"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="coachinginquiry",
            new_name="dashboard_c_status_6dd5c4_idx",
            old_name="dashboard_c_status_2aeebf_idx",
        ),
        migrations.RenameIndex(
            model_name="coachinginquiry",
            new_name="dashboard_c_user_id_a0aba6_idx",
            old_name="dashboard_c_user_id_5d67d4_idx",
        ),
        migrations.AlterField(
            model_name="coachinginquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("contacted", "Contactado"),
                    ("scheduled", "Llamada agendada"),
                    ("qualified", "Cualificado"),
                    ("closed", "Cerrado"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
