# Generated by Django 5.2.4 on 2025-12-21 00:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyWellness",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="Fecha del registro")),
                (
                    "sleep_hours",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Horas de sueño (0-24)",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(24),
                        ],
                    ),
                ),
                (
                    "motivation_score",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "😢 Muy baja"),
                            (2, "😕 Baja"),
                            (3, "😐 Regular"),
                            (4, "🙂 Buena"),
                            (5, "😄 Muy alta"),
                        ],
                        help_text="Nivel de motivación (1-5)",
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Notas adicionales")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_wellness_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Bienestar Diario",
                "verbose_name_plural": "Registros de Bienestar Diario",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="progress_da_user_id_cc60dc_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
