# Generated by Django 5.2.4 on 2026-07-06 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_dailywellness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestWellnessAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(help_text='Array de 32 respuestas booleanas en orden mezclado')),
                ('scores', models.JSONField(help_text='Puntuación por categoría')),
                ('script', models.TextField(help_text='Guión personalizado para el coach')),
                ('top_categories', models.JSONField(help_text='Top 3 categorías prioritarias')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_wellness_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluación de descanso',
                'verbose_name_plural': 'Evaluaciones de descanso',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='progress_re_user_id_f5bde1_idx')],
            },
        ),
    ]
