# Generated by Django 5.2.4 on 2025-11-30 02:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text="Clave única del logro", max_length=100, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("workout", "Entrenamiento"),
                            ("nutrition", "Nutrición"),
                            ("progress", "Progreso"),
                            ("streak", "Racha"),
                            ("milestone", "Hito"),
                            ("social", "Social"),
                            ("system", "Sistema"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, default="", max_length=100)),
                (
                    "criteria",
                    models.JSONField(help_text="Criterios para desbloquear el logro"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0, help_text="Puntos que otorga el logro"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "unlocked_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "progress",
                    models.JSONField(
                        blank=True,
                        help_text="Progreso actual hacia el logro",
                        null=True,
                    ),
                ),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to="achievements.achievement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-unlocked_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "unlocked_at"],
                        name="achievement_user_id_85758b_idx",
                    ),
                    models.Index(
                        fields=["achievement", "unlocked_at"],
                        name="achievement_achieve_b7f334_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "achievement"), name="unique_user_achievement"
                    )
                ],
            },
        ),
    ]
