# Generated by Django 5.2.4 on 2026-01-23 09:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del día (ej: 'Pecho y Tríceps', 'Día de Piernas')",
                        max_length=100,
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        help_text="Número del día en el programa (1, 2, 3...)"
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monday", "Lunes"),
                            ("tuesday", "Martes"),
                            ("wednesday", "Miércoles"),
                            ("thursday", "Jueves"),
                            ("friday", "Viernes"),
                            ("saturday", "Sábado"),
                            ("sunday", "Domingo"),
                        ],
                        help_text="Día de la semana asignado (opcional)",
                        max_length=15,
                    ),
                ),
                (
                    "is_rest_day",
                    models.BooleanField(
                        default=False, help_text="True = día de descanso"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duración estimada en minutos", null=True
                    ),
                ),
                (
                    "focus",
                    models.CharField(
                        blank=True,
                        help_text="Enfoque del día (ej: 'Upper Body', 'Cardio')",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Notas adicionales")),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1, help_text="Orden de visualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Día de Entrenamiento",
                "verbose_name_plural": "Días de Entrenamiento",
                "ordering": ["order_index", "day_number"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Nombre del ejercicio", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción breve"),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Instrucciones de ejecución"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("strength", "Fuerza"),
                            ("cardio", "Cardio"),
                            ("flexibility", "Flexibilidad"),
                            ("hiit", "HIIT"),
                            ("bodyweight", "Peso corporal"),
                            ("functional", "Funcional"),
                            ("plyometrics", "Pliometría"),
                            ("balance", "Equilibrio"),
                        ],
                        default="strength",
                        help_text="Categoría principal",
                        max_length=50,
                    ),
                ),
                (
                    "muscle_groups",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Grupos musculares trabajados ['chest', 'triceps', 'shoulders']",
                    ),
                ),
                (
                    "equipment",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Equipamiento necesario ['dumbbells', 'bench', 'barbell']",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Principiante"),
                            ("intermediate", "Intermedio"),
                            ("advanced", "Avanzado"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True, help_text="URL externa de video (YouTube, Vimeo)"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="URL de imagen del ejercicio"
                    ),
                ),
                (
                    "google_drive_file_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del archivo en Google Drive",
                        max_length=100,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Video subido directamente",
                        null=True,
                        upload_to="exercises/videos/",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="exercises/thumbnails/"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="True = ejercicio del sistema (no eliminable)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False = ejercicio desactivado/oculto"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = ejercicio del sistema",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejercicio",
                "verbose_name_plural": "Ejercicios",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutDayExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sets",
                    models.PositiveIntegerField(
                        default=3, help_text="Número de series"
                    ),
                ),
                (
                    "reps",
                    models.CharField(
                        default="10",
                        help_text="Repeticiones (ej: '10', '8-12', 'hasta fallo')",
                        max_length=50,
                    ),
                ),
                (
                    "weight",
                    models.CharField(
                        blank=True,
                        help_text="Peso (ej: '20kg', 'bodyweight', '70% 1RM')",
                        max_length=50,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duración en segundos (para cardio/planks)",
                        null=True,
                    ),
                ),
                (
                    "rest_seconds",
                    models.PositiveIntegerField(
                        default=60, help_text="Tiempo de descanso entre series"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas técnicas o instrucciones específicas",
                    ),
                ),
                (
                    "order_index",
                    models.PositiveIntegerField(
                        default=1, help_text="Orden del ejercicio en el día"
                    ),
                ),
                (
                    "superset_group",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Grupo de superset (ejercicios con mismo número se hacen juntos)",
                        null=True,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_assignments",
                        to="workouts.exercise",
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="workouts.workoutday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ejercicio en Día",
                "verbose_name_plural": "Ejercicios en Día",
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(help_text="Fecha del entrenamiento")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duración real en minutos", null=True
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, help_text="Si se completó"),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Valoración del entrenamiento (1-5 estrellas)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "exercises_data",
                    models.JSONField(
                        default=list,
                        help_text="Copia de los ejercicios realizados con sets/reps reales",
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Notas del usuario")),
                ("calories_burned", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "average_heart_rate",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workout_day",
                    models.ForeignKey(
                        blank=True,
                        help_text="Día del programa seguido (puede ser null si es libre)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="workouts.workoutday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Entrenamiento",
                "verbose_name_plural": "Logs de Entrenamientos",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutLogExercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise_name",
                    models.CharField(
                        help_text="Nombre del ejercicio (snapshot por si se elimina)",
                        max_length=200,
                    ),
                ),
                ("order_index", models.PositiveIntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workouts.exercise",
                    ),
                ),
                (
                    "workout_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_exercises",
                        to="workouts.workoutlog",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutLogSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("set_number", models.PositiveIntegerField(default=1)),
                ("reps", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso en kg",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("rest_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("completed", models.BooleanField(default=True)),
                (
                    "log_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="workouts.workoutlogexercise",
                    ),
                ),
            ],
            options={
                "ordering": ["set_number"],
            },
        ),
        migrations.CreateModel(
            name="WorkoutProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Nombre del programa", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción del programa"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Principiante"),
                            ("intermediate", "Intermedio"),
                            ("advanced", "Avanzado"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("weight_loss", "Pérdida de peso"),
                            ("muscle_gain", "Ganancia muscular"),
                            ("strength", "Fuerza"),
                            ("endurance", "Resistencia"),
                            ("general_fitness", "Fitness general"),
                            ("body_recomposition", "Recomposición corporal"),
                        ],
                        default="general_fitness",
                        max_length=30,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("gym", "Gimnasio"),
                            ("home", "Casa"),
                            ("outdoor", "Exterior"),
                            ("any", "Cualquier lugar"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                (
                    "duration_weeks",
                    models.PositiveIntegerField(
                        default=4, help_text="Duración en semanas"
                    ),
                ),
                (
                    "days_per_week",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Días de entrenamiento por semana",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "estimated_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duración estimada por sesión en minutos",
                        null=True,
                    ),
                ),
                (
                    "equipment_needed",
                    models.JSONField(
                        blank=True, default=list, help_text="Equipamiento necesario"
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(
                        default=False, help_text="True = plantilla reutilizable"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="True = programa del sistema"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="False = programa inactivo"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Fecha de inicio", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="Fecha de fin", null=True),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("image_url", models.URLField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Quién creó el programa",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workout_programs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario al que pertenece (null = plantilla/sistema)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa de Entrenamiento",
                "verbose_name_plural": "Programas de Entrenamiento",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="workoutday",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="workouts.workoutprogram",
            ),
        ),
        migrations.AddConstraint(
            model_name="workoutlog",
            constraint=models.UniqueConstraint(
                fields=("user", "date", "workout_day"),
                name="unique_workout_log_per_user_day",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workoutday",
            unique_together={("program", "day_number")},
        ),
    ]
