# Generated by Django 5.2.4 on 2025-12-04 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutlog",
            name="rating",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Valoración del entrenamiento (1-5 estrellas)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
