# Generated by Django 5.2.4 on 2026-01-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_alter_workoutlog_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="category",
            field=models.CharField(
                choices=[
                    ("strength", "Fuerza"),
                    ("cardio", "Cardio"),
                    ("flexibility", "Flexibilidad"),
                    ("hiit", "HIIT"),
                    ("bodyweight", "Peso corporal"),
                    ("functional", "Funcional"),
                    ("plyometrics", "Pliometría"),
                    ("balance", "Equilibrio"),
                ],
                default="strength",
                help_text="Categoría principal",
                max_length=50,
            ),
        ),
    ]
