# Generated by Django 5.2.4 on 2026-02-08 10:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_add_plyometrics_and_balance_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseSubstitution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Orden de preferencia (1 = mas recomendado)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas o contexto para usar este sustituto",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        help_text="Ejercicio base que se desea sustituir",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutions",
                        to="workouts.exercise",
                    ),
                ),
                (
                    "substitute",
                    models.ForeignKey(
                        help_text="Ejercicio sustituto",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substituted_in",
                        to="workouts.exercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sustituto de Ejercicio",
                "verbose_name_plural": "Sustitutos de Ejercicios",
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="exercisesubstitution",
            constraint=models.UniqueConstraint(
                fields=("exercise", "substitute"),
                name="unique_exercise_substitute",
            ),
        ),
        migrations.AddConstraint(
            model_name="exercisesubstitution",
            constraint=models.CheckConstraint(
                check=~models.Q(exercise=models.F("substitute")),
                name="exercise_cannot_substitute_itself",
            ),
        ),
    ]
